name: Build and deploy ASP.Net Core app to Azure Web App - rawan33

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./chat/chat

      - name: dotnet publish
        # This command generates the build artifacts (your app's compiled files)
        run: dotnet publish -c Release -o ./myapp
        working-directory: ./chat/chat

      - name: Upload artifact for deployment job
        # This step uploads the generated files (artifacts) for later use
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./chat/chat/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        # This step downloads the build artifacts (published files) for deployment
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9DDC012CC78B400DB23C8644CAAC8695 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B9B57238CBF4A9BB565AD764D8FEF3B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EAB552BF941341E18C24FEAA2901CE0A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rawan33'
          slot-name: 'production'
          package: .
          